Résultats du premier run push button de far ood sur hmdb51

In [52]:
import numpy as np
#import matplotlib.pyplot as plt
import os

# from metrics import compute_all_metrics, acc
from sklearn import metrics
import torch
import pprint

In [2]:
path = "/data/maouche/MultiOOD/EPIC-rgb-flow/saved_files/id_HMDB_ood_EPIC_conf_a2d_npmix_best_eval.npy"
data = np.load(path)
print(data.shape)
print(data)

(4871,)
[0.44259763 0.11941737 0.37215316 ... 0.23253585 0.40844247 0.7723148 ]

**Glossaire des suffixes**

- conf : scores de confiances, cad le max du softmax
- label : les ground truth
- output : les logits tels que retournés par le modèle pour chaque donnée
- feature : feature maps, peut-être à la dernière couche

In [13]:
dir = "/data/maouche/MultiOOD/EPIC-rgb-flow/saved_files"
for file in os.listdir(dir):
    if file.endswith(".npy"):
        data = np.load(path:=os.path.join(dir, file))
        print(path)
        print(data.shape)

/data/maouche/MultiOOD/EPIC-rgb-flow/saved_files/id_HMDB_ood_EPIC_output_a2d_npmix_best_eval.npy
(4871, 43)
/data/maouche/MultiOOD/EPIC-rgb-flow/saved_files/id_HMDB_ood_EPIC_feature_a2d_npmix_best_eval.npy
(4871, 4352)
/data/maouche/MultiOOD/EPIC-rgb-flow/saved_files/id_HMDB_ood_EPIC_conf_a2d_npmix_best_eval.npy
(4871,)
/data/maouche/MultiOOD/EPIC-rgb-flow/saved_files/id_HMDB_ood_EPIC_label_a2d_npmix_best_eval.npy
(4871,)
/data/maouche/MultiOOD/EPIC-rgb-flow/saved_files/id_HMDB_ood_EPIC_pred_a2d_npmix_best_eval.npy
(4871,)

In [ ]:
dir = "/data/maouche/MultiOOD/HMDB-rgb-flow/saved_files"
names = []
sizes = []
for file in os.listdir(dir):
    if file.endswith(".npy"):
        data = np.load(path:=os.path.join(dir, file))
        names.append(path)
        sizes.append(data.shape)

name_size = list(zip(names, sizes))
sorted(name_size, key=lambda x:x[1][0], reverse=False)

[('/data/maouche/MultiOOD/HMDB-rgb-flow/saved_files/id_HMDB_pred_a2d_npmix_best_val.npy',
  (843,)),
 ('/data/maouche/MultiOOD/HMDB-rgb-flow/saved_files/id_HMDB_label_a2d_npmix_best_val.npy',
  (843,)),
 ('/data/maouche/MultiOOD/HMDB-rgb-flow/saved_files/id_HMDB_output_a2d_npmix_best_val.npy',
  (843, 43)),
 ('/data/maouche/MultiOOD/HMDB-rgb-flow/saved_files/id_HMDB_conf_a2d_npmix_best_val.npy',
  (843,)),
 ('/data/maouche/MultiOOD/HMDB-rgb-flow/saved_files/id_HMDB_feature_a2d_npmix_best_val.npy',
  (843, 4352)),
 ('/data/maouche/MultiOOD/HMDB-rgb-flow/saved_files/id_HMDB_feature_a2d_npmix_best_test.npy',
  (877, 4352)),
 ('/data/maouche/MultiOOD/HMDB-rgb-flow/saved_files/id_HMDB_pred_a2d_npmix_best_test.npy',
  (877,)),
 ('/data/maouche/MultiOOD/HMDB-rgb-flow/saved_files/id_HMDB_label_a2d_npmix_best_test.npy',
  (877,)),
 ('/data/maouche/MultiOOD/HMDB-rgb-flow/saved_files/id_HMDB_conf_a2d_npmix_best_test.npy',
  (877,)),
 ('/data/maouche/MultiOOD/HMDB-rgb-flow/saved_files/id_HMDB_output_a2d_npmix_best_test.npy',
  (877, 43)),
 ('/data/maouche/MultiOOD/HMDB-rgb-flow/saved_files/id_HMDB_ood_UCF_feature_a2d_npmix_best_eval.npy',
  (1351, 4352)),
 ('/data/maouche/MultiOOD/HMDB-rgb-flow/saved_files/id_HMDB_ood_UCF_label_a2d_npmix_best_eval.npy',
  (1351,)),
 ('/data/maouche/MultiOOD/HMDB-rgb-flow/saved_files/id_HMDB_ood_UCF_conf_a2d_npmix_best_eval.npy',
  (1351,)),
 ('/data/maouche/MultiOOD/HMDB-rgb-flow/saved_files/id_HMDB_ood_UCF_output_a2d_npmix_best_eval.npy',
  (1351, 43)),
 ('/data/maouche/MultiOOD/HMDB-rgb-flow/saved_files/id_HMDB_ood_UCF_pred_a2d_npmix_best_eval.npy',
  (1351,)),
 ('/data/maouche/MultiOOD/HMDB-rgb-flow/saved_files/id_HMDB_ood_HAC_pred_a2d_npmix_best_eval.npy',
  (3381,)),
 ('/data/maouche/MultiOOD/HMDB-rgb-flow/saved_files/id_HMDB_ood_HAC_conf_a2d_npmix_best_eval.npy',
  (3381,)),
 ('/data/maouche/MultiOOD/HMDB-rgb-flow/saved_files/id_HMDB_ood_HAC_output_a2d_npmix_best_eval.npy',
  (3381, 43)),
 ('/data/maouche/MultiOOD/HMDB-rgb-flow/saved_files/id_HMDB_ood_HAC_label_a2d_npmix_best_eval.npy',
  (3381,)),
 ('/data/maouche/MultiOOD/HMDB-rgb-flow/saved_files/id_HMDB_ood_HAC_feature_a2d_npmix_best_eval.npy',
  (3381, 4352)),
 ('/data/maouche/MultiOOD/HMDB-rgb-flow/saved_files/id_HMDB_conf_a2d_npmix_best_train.npy',
  (3953,)),
 ('/data/maouche/MultiOOD/HMDB-rgb-flow/saved_files/id_HMDB_feature_a2d_npmix_best_train.npy',
  (3953, 4352)),
 ('/data/maouche/MultiOOD/HMDB-rgb-flow/saved_files/id_HMDB_output_a2d_npmix_best_train.npy',
  (3953, 43)),
 ('/data/maouche/MultiOOD/HMDB-rgb-flow/saved_files/id_HMDB_label_a2d_npmix_best_train.npy',
  (3953,)),
 ('/data/maouche/MultiOOD/HMDB-rgb-flow/saved_files/id_HMDB_pred_a2d_npmix_best_train.npy',
  (3953,))]

# Signification des suffixes

Les fichiers **pred** contiennent les classes prédites par le modèle. Il y a 843 fichiers dans le split val

In [3]:
path = "/data/maouche/MultiOOD/HMDB-rgb-flow/saved_files/id_HMDB_pred_a2d_npmix_best_val.npy"
data = np.load(path)
print(data.shape)
print(data)

(843,)
[ 0  0  0  0  0 34  0  0  0  8  0  0  0  0  0  0  1  1  1  1  1  1  1  1
  1 10 10  1  1  1  1  1  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  3
  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3 39  3  4  4  4  4  4  4
  4  4  4  4  4  4  4  4  5  5  5  5  5  5  5  5  5  5  5  8  5  5  5  5
  5 34  6  6  6  6  6  0  6  6  6  6  6  6  6  6  8  7  7  7  7  7  7  7
  7  7  7  7  7  7  7  7 26  7  7  7  7  7  7  8  8  8  8  8  8  8  8  8
  8  8  8  8  8  8  8  8  8  8  8  9  9  9  9  9  9 36  9  9 36  9  9  9
  9  9  9  9 10 10 10 33 10 10 10 10 33 10 10 10 10 10 10 10 11 11 11 11
 11 11 11 11 11 11 11 11 11 11 11 11 12 12 12 12 12  1  1 12  1 12 12 12
 12 12 12 12 12 41 13 13 13 13 13 21 21 13 13 13 13 13 13 13 13 13 13 13
 14 14 14 14 14 14 14 14 14 14 14 14 14 14 18 14 14 14 15 29 40 15  5 15
  5 15 15 15 15 15 15 15 39 15 15 15 15  8  5 15 15 16 16 16 16 16  8 16
 16 16 16 16 16 16 16 16 16 29 16 34 16 17 17 17 17 17 17 17 17 17 17 17
 17 17 17 17 17 17 17 18 31 18 18 18 18 18 18 18 18 14 18 18 18 18 19 19
 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 20 20 20 20 20 20 20
 20 20 20 20 20 20 20 20 20 21 21 21 21 36 21 21 21 34 16 13 21 21 21 13
 21 13 21 21 41 22 41 22 22 22 22 22 22 22 22 22 22 22 22 22 22 23 23 23
 23 23 23 23 23 23 23 23 23 23 23 23 24 24 24 24 24 24 24 24 24 41 24 24
 24 24 24 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25
 25 25 14 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 27
 27 27 27 27 27 27 27 27 27 27 27 27 27 27 27 27 28 28 28 28  5 28 28 14
 28 28 28 28 28 29 29 29 29 29 29 29 29 41 29 29 29 29 29 29 29 29 29 29
 29 29 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 31 31 31 31 31 31
 38 31 31 31 31 31 31 40 31 32 32 32 32 32 32 32 32 34 32 32 32 32 32 32
 32 33 33 33 33 33 33 33  5 33  8 33 33 33 33 33  5  5 33 33 33 34 34 34
 29 40 41 34 34 34 34 34 25 34 34 34 34 34 34 34 34 34 34 41 35 35 35 35
 39 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 36 36 36 36 36 36 21
  6 36 36 36 36 36 36 36 36 36 36 36 37 37 25 37 37 37 37 37 37 36 28 37
  6  6 37 37 37 37 37 38 38 38 38 41 38 38 38 38 38 38 38  3 38 38 38 40
 39 39 39 21 39 39 39 41 39 39 42 35 39 16 40 40 40 41 40 28 40 40 34 40
 40 40 40 40 40 40 40 27 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40
 40 40 41 41 41 40 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41
 41 41 42 17 41 41 41 41 41 41 41 41 41 41 34 41 41 41 41 41 41 41 41 41
 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 28 41 41 25 41 41 41 41
 41 41 41 41 41 41 41 41 41 41 41 15 42 42 42 31 29 42 42 42 42 42 42 34
 42 42 42]

Les fichiers **label**  contiennent les ground truth.

In [4]:
path = "/data/maouche/MultiOOD/HMDB-rgb-flow/saved_files/id_HMDB_label_a2d_npmix_best_val.npy"
data = np.load(path)
print(data.shape)
print(data)

(843,)
[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  1  1  1  1  1  1  1
  1  1  1  1  1  1  1  1  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  3
  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  4  4  4  4  4  4
  4  4  4  4  4  4  4  4  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5
  5  5  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  7  7  7  7  7  7  7
  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7  8  8  8  8  8  8  8  8  8
  8  8  8  8  8  8  8  8  8  8  8  9  9  9  9  9  9  9  9  9  9  9  9  9
  9  9  9  9 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 11 11 11 11
 11 11 11 11 11 11 11 11 11 11 11 11 12 12 12 12 12 12 12 12 12 12 12 12
 12 12 12 12 12 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13
 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 15 15 15 15 15 15
 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 16 16 16 16 16 16 16
 16 16 16 16 16 16 16 16 16 16 16 16 17 17 17 17 17 17 17 17 17 17 17 17
 17 17 17 17 17 17 17 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 19 19
 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 20 20 20 20 20 20 20
 20 20 20 20 20 20 20 20 20 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21
 21 21 21 21 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 23 23 23
 23 23 23 23 23 23 23 23 23 23 23 23 24 24 24 24 24 24 24 24 24 24 24 24
 24 24 24 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25
 25 25 25 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 27
 27 27 27 27 27 27 27 27 27 27 27 27 27 27 27 27 28 28 28 28 28 28 28 28
 28 28 28 28 28 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29
 29 29 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 31 31 31 31 31 31
 31 31 31 31 31 31 31 31 31 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32
 32 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 34 34 34
 34 34 34 34 34 34 34 34 34 34 34 34 34 34 34 34 34 34 34 34 35 35 35 35
 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 36 36 36 36 36 36 36
 36 36 36 36 36 36 36 36 36 36 36 36 37 37 37 37 37 37 37 37 37 37 37 37
 37 37 37 37 37 37 37 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38
 39 39 39 39 39 39 39 39 39 39 39 39 39 39 40 40 40 40 40 40 40 40 40 40
 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40
 40 40 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41
 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41
 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41
 41 41 41 41 41 41 41 41 41 41 41 41 42 42 42 42 42 42 42 42 42 42 42 42
 42 42 42]

Les fichiers **output** contiennent les **logits**. 842 pour le nombre d'exemples et 43 pour le nombre de classes

In [5]:
path = "/data/maouche/MultiOOD/HMDB-rgb-flow/saved_files/id_HMDB_output_a2d_npmix_best_val.npy"
data = np.load(path)
print(data.shape)
print(data)

(843, 43)
[[  9.551006  -11.218089  -11.223899  ...  -7.963518   -6.9919205
   -8.55932  ]
 [  4.3062124 -11.8711    -11.465627  ...  -8.242423   -9.513602
   -6.135794 ]
 [  9.450798  -11.7504    -11.7918    ...  -7.7297983  -7.9175467
   -6.822984 ]
 ...
 [ -9.226287  -12.298967  -10.585246  ...  -7.449084  -11.904885
   10.397236 ]
 [ -4.497591  -11.434968   -8.496568  ...  -3.55011    -4.1009235
   -0.3867626]
 [-10.489369  -14.052661   -8.822249  ...  -6.165988  -11.213553
   12.434434 ]]

Les fichiers **conf** contiennent les scores de confiance, c-a-d les **max des softmax**

In [6]:
path = "/data/maouche/MultiOOD/HMDB-rgb-flow/saved_files/id_HMDB_conf_a2d_npmix_best_val.npy"
data = np.load(path)
print(data.shape)
print(data)

(843,)
[0.9999956  0.99937564 0.9999931  0.9999454  0.99964595 0.9751288
 0.9999999  1.         0.9999994  0.8223828  0.9996555  0.99999845
 0.99982196 0.8651386  0.9999982  1.         0.9912731  0.92672837
 0.5455324  0.99821717 1.         0.7314217  0.99301916 0.99979883
 0.9999956  0.5190761  0.9068743  0.99769753 0.9984653  0.999858
 0.9998797  0.809282   0.99996316 0.99999154 0.99999166 0.99998116
 0.99997187 0.99997604 0.99989736 0.9999999  0.999997   0.99458003
 0.98823404 0.9999924  0.99497825 0.9999641  0.9981255  1.
 1.         0.9999995  0.9999962  0.9999988  0.9999906  0.9999999
 0.99999857 0.99964595 0.99998534 1.         0.999977   1.
 0.9999981  0.9999989  0.9999989  0.99999976 0.64893293 0.99989235
 0.9999572  0.9998486  0.99973017 0.99935466 0.99769163 0.9388575
 0.70876926 0.9997515  0.99997723 0.9999584  0.9992725  0.9999701
 0.9998553  0.9998956  0.99999595 0.9787617  1.         0.99999726
 1.         0.9999999  0.99988914 0.99937254 0.9999683  0.9999962
 0.9999927  0.9975587  0.99853015 0.9787758  0.9995296  0.99999905
 0.8337687  0.8410567  0.99998486 0.639331   0.99999905 0.99803144
 0.5805389  0.67120343 0.99998116 0.99857986 0.9999981  0.9301208
 0.99680495 0.9998957  0.6540305  0.9822015  0.5582391  0.99999166
 0.9586805  0.9998684  0.99976104 0.9999968  0.99996614 0.99997985
 0.9999881  0.9999958  0.99999    0.99996805 0.99997246 0.9498344
 0.99575585 0.8721178  0.9966928  0.9999982  0.9999708  0.9999161
 0.9999994  0.9999994  0.9999975  0.9915685  0.9696676  0.99958354
 0.6236392  0.9999962  0.9998424  0.8843441  0.82886404 0.72057164
 0.9456155  0.95247453 0.99925905 0.9999976  0.8207538  0.83931905
 0.90852064 0.78119123 0.99983895 0.9666767  0.96726495 0.9999912
 0.9999999  0.9999596  0.9999995  0.9995334  0.9999554  0.6687751
 0.9999988  0.9990577  0.92482597 0.99999905 0.89245564 0.99999356
 0.9986798  0.999678   0.9999989  0.9491055  0.99999964 0.999995
 0.9998267  0.62664735 0.9999939  0.9999789  0.99995494 0.99999106
 0.9995308  0.99999046 0.99999976 0.9957163  0.99999225 0.99999475
 0.999421   0.9999573  1.         1.         0.99596393 1.
 0.9999919  1.         1.         0.9999249  1.         1.
 0.9998853  1.         1.         0.99998975 0.9998485  0.99999964
 0.9488946  0.9999962  0.9999999  0.9999027  1.         0.6759965
 0.94321775 0.9999715  0.53313893 1.         0.9997497  0.9999682
 0.9848225  0.9999994  0.9999988  0.999985   0.99999285 0.9999857
 0.99823004 0.99999976 0.99850744 0.9999628  0.9999912  0.5608977
 0.764029   0.9999361  0.9999089  0.9999902  0.9999782  0.9258903
 0.7948635  0.99944204 0.9999695  0.74651694 0.9989374  0.99977404
 1.         0.9999999  0.9999999  0.99999404 0.99999964 1.
 0.9999808  0.99999976 1.         0.999998   0.99999964 0.999716
 0.9981554  0.9999877  0.7287406  0.999972   0.9999976  1.
 0.68955326 0.4994379  0.47133684 0.99403715 0.9983802  0.94351417
 0.5464215  0.9381809  0.8204477  0.8215923  0.99945956 0.99973685
 0.8916022  0.99999976 0.99562526 0.8170429  0.5359334  0.85842323
 0.9383947  0.8671196  0.5978137  0.9974166  0.9998697  0.9999559
 0.99999094 0.9907452  0.9774948  0.9998349  0.38921186 0.9497682
 0.9614955  0.996102   0.99769837 0.9997135  0.98488635 0.9998815
 0.92177707 0.8015556  0.99830127 0.49242595 0.99993443 0.57081157
 0.8798399  0.99999666 0.9773588  0.9978987  0.9999144  0.9999677
 0.9997017  0.9694184  0.9998932  0.9997435  1.         0.99997926
 0.97341365 0.99998665 0.9999933  0.99980694 0.9935766  0.9999844
 0.9995454  0.86849624 0.99137396 1.         0.9999999  0.9999993
 0.9997676  1.         0.9963096  0.9999931  0.999869   0.99691665
 0.9999994  0.99999475 0.99998665 0.99999547 0.9999536  0.9999728
 0.9999993  0.99999976 0.9999989  0.99991655 0.99989164 0.9999993
 0.9999949  0.9999815  0.99999976 0.99964094 0.97090256 0.9999968
 0.99990594 0.9999635  0.9800741  0.9996855  1.         0.99997735
 0.9999974  0.9999981  0.9999232  0.9999995  0.99999857 0.99999905
 0.99999964 0.9999999  0.99999845 0.99999285 0.99999774 0.99999976
 0.99999857 0.99993813 0.9999999  0.99999964 0.9962714  1.
 0.9999995  0.7783282  0.98754466 0.99995303 0.99999905 0.91125363
 0.916212   0.9187319  0.99999976 0.9999968  0.9999999  0.74923414
 0.9999827  0.85013795 0.9999994  0.5866646  0.282899   0.9999995
 0.818367   0.9999114  0.999632   0.9999033  0.9999492  0.9999896
 0.99966156 0.9999957  0.99975544 0.99990666 0.999522   0.9999702
 0.9999707  0.99982965 0.9992187  0.9999999  0.99999976 0.9999994
 0.9998301  0.9999995  0.9999995  0.9999999  0.99999905 0.99999976
 0.9998047  1.         1.         0.9999393  0.99991    1.
 1.         1.         0.99999607 1.         1.         1.
 1.         1.         0.9999994  0.80412257 1.         1.
 1.         0.9999999  0.99999857 1.         0.99999905 0.99999654
 0.9981262  1.         0.999987   1.         0.999941   1.
 0.9997234  1.         0.9999994  0.9999987  0.9999523  1.
 0.99989915 1.         0.9999999  0.99999976 0.9995066  0.99994314
 0.9999733  0.99996066 0.97106385 0.9999999  0.9999418  0.99999964
 0.9999894  0.99999976 0.99998546 0.9999989  0.9998704  0.9999889
 1.         0.9999995  0.99999475 0.999676   0.99930143 0.9999989
 0.9931378  0.99999523 0.999997   0.9999975  0.99939775 1.
 0.99999666 1.         0.9999962  0.99999917 1.         0.9999999
 0.9999902  0.9992818  1.         1.         0.94989884 0.97592884
 1.         0.99999976 0.9999981  0.9999968  0.9999832  0.9995633
 0.9999999  0.999997   0.9841559  1.         0.9999994  0.64097744
 0.99997854 0.99999774 1.         0.99999523 0.9928167  0.98969954
 0.9977677  0.97176987 0.7001473  0.99986804 0.9846505  0.9872873
 0.98538464 0.6490706  0.9993017  0.995061   0.87181807 0.995478
 0.8731467  0.5749231  0.9999231  0.9846373  0.9998714  0.99912566
 0.9997397  0.80419785 0.9999932  0.99999666 1.         0.9999943
 0.99999857 0.9999602  0.99996936 1.         1.         0.99999845
 0.9999702  1.         0.999998   0.99999475 0.9991714  1.
 0.9898638  0.99998283 0.9999999  0.99965024 0.9985012  0.9992499
 0.9926602  0.9999292  0.9995296  0.99996877 0.99829966 0.9999981
 0.9999895  0.22176267 0.9999933  0.9996544  0.99963677 0.89645046
 0.99999976 0.999689   1.         1.         1.         0.873988
 0.9972059  1.         0.9972031  0.7144876  0.99999964 0.9999713
 0.9999938  0.999982   0.99998915 0.99998987 0.99764204 0.9999951
 0.9997763  0.9997608  0.80302423 0.99995506 0.82078356 0.9999956
 0.99986744 0.99998343 0.99907947 0.9999914  0.6579747  0.71195626
 0.9989773  0.99586076 0.9481786  0.5019431  0.9979572  0.9541998
 0.41295826 0.54807675 0.8678837  0.6687871  0.5062667  0.9712567
 0.75822836 0.92105675 0.9988844  0.9973309  0.9950352  0.9997391
 0.9970886  0.9999324  0.99995553 0.9312917  0.7002438  0.94472593
 0.9998467  0.9964257  0.9999616  0.9999522  0.99999774 0.9999727
 0.82572746 0.92343426 0.999843   0.9931479  0.9999871  0.9992508
 0.997306   0.9874905  0.99998665 0.99999106 0.97914493 0.9999144
 0.9999708  0.9994591  0.99999523 0.9999089  0.99998903 0.9999902
 0.9654996  0.99964464 0.5746717  0.9989969  0.99998176 0.6071339
 0.6777141  0.986387   0.99997306 0.8643948  0.9999585  0.99995995
 0.9994842  0.99735945 0.9910138  0.9929212  0.98943007 0.9710391
 0.9413277  0.9960349  0.39099956 0.99939597 0.9999964  0.99929273
 0.9999325  0.9998759  0.999099   0.9687159  0.68901366 0.9999056
 0.81679785 0.9951498  0.9963755  0.99379325 0.9934895  0.9986656
 0.9997409  0.9999609  0.9999862  0.94570005 0.9919675  0.30508083
 0.9999975  0.99999416 0.9985251  0.98521245 0.99962795 0.99543226
 0.999997   0.7102826  0.9995906  0.6654621  0.99990964 0.97031116
 0.8848855  0.9968143  0.9999056  0.739043   0.99999976 0.9784823
 0.99602914 0.5703335  0.99998605 0.72908056 0.86144024 0.92172176
 0.99999213 0.53740174 0.9996699  0.89022756 0.99634415 0.9671018
 0.99684095 0.9291171  0.8516917  0.98343    0.33657405 0.99999166
 0.9999181  0.7076479  0.99954873 0.99997437 0.9477922  0.9895752
 0.9998692  0.46520624 0.99992895 0.99992085 0.999967   0.9962328
 0.99991643 0.99998987 0.9997286  0.99987185 0.99997616 0.999987
 0.99999607 0.9977952  0.9228829  0.99668795 0.9949274  0.92198634
 0.77343065 0.99969065 0.9992473  0.9985335  0.99999976 0.9700493
 0.99971884 0.99998724 0.99050796 0.99998665 0.9741338  0.9998692
 0.9999988  0.99998426 0.99962807 0.9996253  0.9985556  0.99999344
 0.99943966 0.9997882  0.9999181  0.9963593  0.9974178  0.9999995
 0.998944   0.9999511  0.26439512 0.9919497  0.9999995  0.9964133
 0.99871945 0.9999207  0.99993634 0.6150271  0.9991596  0.9943516
 0.9999727  0.9937895  0.5265193  0.99998903 0.9999963  0.30902845
 0.9768862  0.9880023  0.9999918  0.82942736 0.9999995  0.99716175
 0.9999982  0.9999956  0.9996995  0.9999962  0.8657172  0.99845254
 0.9999931  0.9996265  0.956559   0.99073225 0.99996674 1.
 0.9969348  0.99999475 0.999979   0.9999937  0.98534447 0.99816626
 0.99908054 0.28977668 0.99999607 0.99994326 0.9972609  0.9999906
 0.99999917 0.9999888  0.9998802  0.99999464 0.99983835 0.1991361
 0.9951191  0.9999232  0.9999243  0.9999567  0.99945956 0.85123813
 0.8356487  0.5635793  0.72343165 0.5893129  0.65831983 0.55540454
 0.99999857 0.9872301  0.96967757 0.9977089  0.99999976 0.87217766
 0.9999995  0.66128105 0.9999999 ]

In [ ]:
path = "/data/maouche/MultiOOD/EPIC-rgb-flow/saved_files/id_HMDB_ood_EPIC_conf_a2d_npmix_best_eval.npy"
data = np.load(path)
print(data.shape)
print(data)
print(data.mean())
print(data.std())

# Reconstitution des résultats

## HMDB ID vs UCF OOD eval

In [ ]:
config = "/data/maouche/MultiOOD/HMDB-rgb-flow/saved_files/id_HMDB_ood_{}_{}_a2d_npmix_best_eval.npy"
#"/data/maouche/MultiOOD/EPIC-rgb-flow/saved_files/id_HMDB_ood_EPIC_output_a2d_npmix_best_eval.npy"
ood_datasets = ['UCF', 'HAC']
cases = ["pred", "label", "output", "conf", "feature"]

Calculer les métriques

In [25]:
dataset = "UCF"
all_results_ucf = {}
for case in cases:
    path = config.format(dataset, case)
    all_results_ucf[case] = np.load(path)

#for case in cases:
print(all_results_ucf["label"])

[ 0  0  0 ... 94 94 94]

In [27]:
dataset = "UCF"
all_results_ucf = {}
for case in cases:
    path = config.format(dataset, case)
    all_results_ucf[case] = np.load(path)

fpr, auroc, aupr_in, aupr_out, accuracy = compute_all_metrics(all_results_ucf.get("conf",-1), 
                                            all_results_ucf.get("label", -1), all_results_ucf.get("pred", -1))

/home/maouche/.conda/envs/multiood/lib/python3.8/site-packages/sklearn/metrics/_ranking.py:1133: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
/home/maouche/.conda/envs/multiood/lib/python3.8/site-packages/sklearn/metrics/_ranking.py:980: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(

In [28]:
fpr, auroc, aupr_in, aupr_out, accuracy

(0.0, nan, 1.0, 0.5, 0.008882309400444115)

## réimplementation

In [53]:
ood_datasets = ["UCF", "EPIC", "HAC"]
pooling_types = ["max", "mean", "min"]

In [13]:
def compute_all_metrics(conf, label, pred):
    np.set_printoptions(precision=3)
    recall = 0.95
    auroc, aupr_in, aupr_out, fpr = auc_and_fpr_recall(conf, label, recall)

    accuracy = acc(pred, label)

    results = [fpr, auroc, aupr_in, aupr_out, accuracy]

    return results


# accuracy
def acc(pred, label):
    ind_pred = pred[label != -1]
    ind_label = label[label != -1]

    num_tp = np.sum(ind_pred == ind_label)
    acc = num_tp / len(ind_label)

    return acc


def auc_and_fpr_recall(conf, label, tpr_th):
    # following convention in ML we treat OOD as positive
    ood_indicator = label
    #ood_indicator = np.zeros(label)
    #ood_indicator[label == -1] = 1

    # in the postprocessor we assume ID samples will have larger
    # "conf" values than OOD samples
    # therefore here we need to negate the "conf" values
    fpr_list, tpr_list, thresholds = metrics.roc_curve(ood_indicator, -conf)
    fpr = fpr_list[np.argmax(tpr_list >= tpr_th)]

    precision_in, recall_in, thresholds_in \
        = metrics.precision_recall_curve(1 - ood_indicator, conf)

    precision_out, recall_out, thresholds_out \
        = metrics.precision_recall_curve(ood_indicator, -conf)

    auroc = metrics.auc(fpr_list, tpr_list)
    aupr_in = metrics.auc(recall_in, precision_in)
    aupr_out = metrics.auc(recall_out, precision_out)

    return auroc, aupr_in, aupr_out, fpr

In [ ]:
#auc_and_fpr_recall(all_results_ucf.get("conf",-1), all_results_ucf.get("label",-1), tpr_th=0.95)
# auroc, aupr_in, aupr_out, fpr

/home/maouche/.conda/envs/multiood/lib/python3.8/site-packages/sklearn/metrics/_ranking.py:1124: UndefinedMetricWarning: No negative samples in y_true, false positive value should be meaningless
  warnings.warn(
/home/maouche/.conda/envs/multiood/lib/python3.8/site-packages/sklearn/metrics/_ranking.py:980: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(

(nan, 0.5, 0.9999999999999999, nan)

Pour calculer la AUC et FPR, il faut les ground truth ID et OOD. Il faut donc combiner les résultats sur HMDB (j'ai pris le split val) avec les résultats sur le dataset OOD.
Aussi, dans leur fonction, ils mettent à 1 les valeurs égales à -1 dans les labels, sauf qu'en aucun cas on a un label de -1, donc avec leur implémentation on n'a jamais de label positif, d'où le warning

Là je fais de la **MSP** avec  npmix et a2d

In [12]:
def get_result(ood_dataset=None, case="conf", mode='val'):
    if ood_dataset == "EPIC":
        path = f"/data/maouche/MultiOOD/EPIC-rgb-flow/saved_files/id_HMDB_ood_EPIC_{case}_a2d_npmix_best_eval.npy"
    elif ood_dataset == None:
        path = f'/data/maouche/MultiOOD/HMDB-rgb-flow/saved_files/id_HMDB_{case}_a2d_npmix_best_{mode}.npy'
    else:
        path =  f"/data/maouche/MultiOOD/HMDB-rgb-flow/saved_files/id_HMDB_ood_{ood_dataset}_{case}_a2d_npmix_best_eval.npy"    
    return np.load(path)

In [ ]:
#combiner resultats HMDB et UCF pour avoir positifs et negatifs
#concaténer les conf et label

conf_hmdb = get_result(None, "conf", "val")
label_hmdb = get_result(None, "label")
conf_ucf = get_result("UCF", "conf")
label_ucf = get_result("UCF", "label")

conf_combine = np.hstack((conf_hmdb, conf_ucf))
label_combine = np.hstack((np.zeros_like(conf_hmdb), np.ones_like(label_ucf)))

In [57]:
auc_and_fpr_recall(conf_combine, label_combine, tpr_th=0.95)
# auroc, aupr_in, aupr_out, fpr

(0.889063327283599, 0.8536506758208082, 0.9162875427029971, 0.3973902728351127)

In [10]:
def compute_metrics(ood_dataset):
    conf_id = get_result(None, "conf", "val") #id est hmdb
    conf_ood = get_result(ood_dataset, "conf")
    pred_id = get_result(None, "pred", "val")
    pred_ood = get_result(ood_dataset, "pred")
    
    conf_combine = np.hstack((conf_id, conf_ood))
    label_combine = np.hstack((np.zeros_like(conf_id), np.ones_like(conf_ood)))
    pred_combine = np.hstack((pred_id, pred_ood))
    
    return compute_all_metrics(conf_combine, label_combine, pred_combine) 
    # fpr, auroc, aupr_in, aupr_out, accuracy

In [ ]:
results = {}

for dataset in ood_datasets:
    fpr, auroc, aupr_in, aupr_out, accuracy = compute_metrics(dataset)
    results.setdefault(dataset, {})
    results[dataset]["auroc"] = auroc
    results[dataset]["fpr"] = fpr

In [67]:
results

{'UCF': {'auroc': 0.889063327283599, 'fpr': 0.3973902728351127},
 'HAC': {'auroc': 0.9250053417622658, 'fpr': 0.27164887307236063},
 'EPIC': {'auroc': 0.9717896096514268, 'fpr': 0.12930011862396204}}

# Max/Mean/Min SP

Pour Mean et Min:
- récupérer les fichiers 'output' (logits) et appliquer un softmax
- Prendre le mean

In [ ]:
output_hmdb = get_result(ood_dataset=None, case="output", mode='val')
#output_ood = get_result(ood_dataset="UCF", case="output")

sm_hmdb = torch.softmax(torch.tensor(output_hmdb), dim=1)
means_sm_hmdb = torch.mean(sm_hmdb, dim=1)
min_sm_hmdb = torch.min(sm_hmdb, dim=1)

In [39]:
def compute_metrics_sp(ood_dataset, pooling="max"): 
    #mode = {max, mean, min} max est équivalent à loader conf mais pour min et mean il faut loader output et faire softmax et prendre le min ou mean à la main
    assert pooling in {"max", "mean", "min"}
    
    if pooling == "max":
        conf_id = get_result(None, "conf", "val") #id est hmdb
        conf_ood = get_result(ood_dataset, "conf")

    else:
        output_id = get_result(ood_dataset=None, case="output", mode='val')
        output_ood = get_result(ood_dataset, case="output")
        
        sm_id = torch.softmax(torch.tensor(output_id), dim=1)
        sm_ood = torch.softmax(torch.tensor(output_ood), dim=1)
        if pooling == "mean":
            conf_id = torch.mean(sm_id, dim=1) 
            conf_ood = torch.mean(sm_ood, dim=1) 
            
        elif pooling == "min":
            conf_id = torch.min(sm_id, dim=1)[0]
            conf_ood = torch.min(sm_ood, dim=1)[0] 
            # print(conf_id)
            # print(conf_ood)
    
    pred_id = get_result(None, "pred", "val") # quand je fais le min, est ce que je prends comme pred le max ? jpense oui
    pred_ood = get_result(ood_dataset, "pred")
    
    conf_combine = np.hstack((conf_id, conf_ood))
    label_combine = np.hstack((np.zeros_like(conf_id), np.ones_like(conf_ood)))
    pred_combine = np.hstack((pred_id, pred_ood))
    
    
    return compute_all_metrics(conf_combine, label_combine, pred_combine) 
    # fpr, auroc, aupr_in, aupr_out, accuracy

In [54]:
results = {}

for pooling in pooling_types:
    results.setdefault(pooling, {})
    
    for dataset in ood_datasets:
        results.get(pooling,-1).setdefault(dataset, {})
        fpr, auroc, aupr_in, aupr_out, accuracy = compute_metrics_sp(dataset, pooling)
        #results.get(pooling,-1).get(dataset,-1).setdefault(dataset, {})
        results.get(pooling,-1).get(dataset,-1)["auroc"] = auroc
        results.get(pooling,-1).get(dataset,-1)["fpr"] = fpr

In [55]:
pprint.pp(results)

{'max': {'UCF': {'auroc': 0.889063327283599, 'fpr': 0.3973902728351127},
         'EPIC': {'auroc': 0.9717896096514268, 'fpr': 0.12930011862396204},
         'HAC': {'auroc': 0.9250053417622658, 'fpr': 0.27164887307236063}},
 'mean': {'UCF': {'auroc': 0.5238147920831896, 'fpr': 0.9596678529062871},
          'EPIC': {'auroc': 0.5172089980817062, 'fpr': 0.9596678529062871},
          'HAC': {'auroc': 0.5157263586232884, 'fpr': 0.9596678529062871}},
 'min': {'UCF': {'auroc': 0.07418870780661571, 'fpr': 1.0},
         'EPIC': {'auroc': 0.008952200461101636, 'fpr': 1.0},
         'HAC': {'auroc': 0.04851653385063345, 'fpr': 1.0}}}

# Phase 2

In [1]:
import pandas as pd

In [25]:
results_file = "results_postprocessings.csv"
df_results = pd.read_csv(results_file)

In [26]:
ordre_method = ['msp', 'ebo', 'maxlogit', 'Mahalanobis', 'react', 'ash', 'gen', 'knn', 'vim']
ordre_dataset = ['UCF', 'EPIC', 'HAC']
ordre_layer_proc = ['none', 'ash', 'react']

In [ ]:
df_results['method'] = pd.Categorical(df_results['method'], categories=ordre_method, ordered=True)
#df_results['dataset'] = pd.Categorical(df_results['dataset'], categories=ordre_dataset, ordered=True)
df_results['layer_proc'] = pd.Categorical(df_results['layer_proc'], categories=ordre_layer_proc, ordered=True)

# Trier d'abord par 'method', puis par 'dataset'
df_results = df_results.sort_values(['method', 'layer_proc']) #['method', 'dataset', 'layer_proc']
df_results.fpr95 = df_results.fpr95.apply(lambda x:x*100)
df_results.auroc = df_results.auroc.apply(lambda x:x*100)
df_results.id_acc = df_results.id_acc.apply(lambda x:x*100)

df_results.fpr95 = df_results.fpr95.apply(lambda x:np.round(x,3))
df_results.auroc = df_results.auroc.apply(lambda x:np.round(x,3))
df_results.id_acc = df_results.id_acc.apply(lambda x:np.round(x,3))

In [3]:
#df_results.to_csv("full_results.csv", index=False)
df_results = pd.read_csv("full_results.csv")

In [31]:
df_results

   method dataset layer_proc   fpr95   auroc  id_acc       exec_time
0     msp     UCF       none  40.593  88.000  86.773             NaN
1     msp     HAC       none  28.620  91.568  86.773             NaN
2     msp    EPIC       none  13.455  96.422  86.773             NaN
3     msp     UCF        ash  41.505  86.432  86.203  0:00:00.027182
4     msp     HAC        ash  28.734  90.328  86.203  0:00:00.042857
..    ...     ...        ...     ...     ...     ...             ...
64    vim     HAC        ash  14.481  96.614  86.203  0:00:48.589382
65    vim    EPIC        ash  10.376  96.863  86.203  0:00:49.204083
66    vim     UCF      react  29.190  91.534  86.545  0:00:45.662581
67    vim     HAC      react   9.122  98.180  86.545  0:00:47.869842
68    vim    EPIC      react   6.956  97.389  86.545  0:00:49.063331

[69 rows x 7 columns]

In [8]:
vanilla_methods = df_results[df_results.layer_proc=="none"]
ash_react = df_results[df_results.method.isin(["ash", "react"])]

reimpl_papier = pd.concat([vanilla_methods, ash_react])
reimpl_papier['method'] = pd.Categorical(reimpl_papier['method'], categories=ordre_method, ordered=True)
reimpl_papier = reimpl_papier.sort_values(['method', 'layer_proc']) #['method', 'dataset', 'layer_proc']

reimpl_papier

,method,dataset,layer_proc,fpr95,auroc,id_acc,exec_time
6,msp,UCF,none,40.592930,88.000020,86.773090,NaN
7,msp,HAC,none,28.620296,91.567944,86.773090,NaN
8,msp,EPIC,none,13.454960,96.422314,86.773090,NaN
15,ebo,UCF,none,37.058153,89.712000,86.773090,NaN
16,ebo,HAC,none,23.033067,94.447204,86.773090,NaN
17,ebo,EPIC,none,7.183580,97.597912,86.773090,NaN
3,maxlogit,UCF,none,37.058153,89.728627,86.773090,NaN
4,maxlogit,HAC,none,23.147092,94.250283,86.773090,NaN
5,maxlogit,EPIC,none,7.069555,97.725678,86.773090,NaN
0,Mahalanobis,UCF,none,27.708096,91.210869,86.773090,NaN
1,Mahalanobis,HAC,none,7.753706,98.217789,86.773090,NaN
2,Mahalanobis,EPIC,none,12.428734,96.100277,86.773090,NaN
21,react,UCF,react,37.286203,89.684823,86.545040,0:00:00.391833
22,react,HAC,react,20.866591,95.056316,86.545040,0:00:00.553978
23,react,EPIC,react,7.183580,97.457880,86.545040,0:00:01.281754
18,ash,UCF,ash,38.768529,89.552230,86.202965,0:00:00.530498
19,ash,HAC,ash,23.489168,94.481570,86.202965,0:00:00.626123
20,ash,EPIC,ash,6.955530,98.250812,86.202965,0:00:00.932298
9,gen,UCF,none,37.400228,91.234754,86.773090,NaN
10,gen,HAC,none,24.287343,94.326131,86.773090,NaN
11,gen,EPIC,none,5.131129,99.024291,86.773090,NaN
12,knn,UCF,none,33.181300,91.948360,86.773090,NaN
13,knn,HAC,none,13.568985,97.247716,86.773090,NaN
14,knn,EPIC,none,5.587229,98.989821,86.773090,NaN
66,vim,UCF,none,26.909920,92.274146,86.773090,0:00:55.357998
67,vim,HAC,none,6.385405,98.563001,86.773090,0:00:47.698387
68,vim,EPIC,none,5.587229,98.062416,86.773090,0:00:49.830122

In [ ]:
#reimpl_papier.to_csv("reimpl_papier.csv", index=False)
reimpl_papier = pd.read_csv("reimpl_papier.csv")

In [43]:
metrics_none = df_results[df_results.layer_proc=="none"][["method", "dataset", "fpr95", "auroc", "id_acc"]].reset_index()
metrics_ash = df_results[df_results.layer_proc=="ash"][["method", "dataset", "fpr95", "auroc", "id_acc"]].reset_index()
metrics_react = df_results[df_results.layer_proc=="react"][["method", "dataset", "fpr95", "auroc", "id_acc"]].reset_index()
metrics_diff = metrics_none.copy()

In [44]:
metrics_diff["ash_diff_fpr"] = metrics_ash.fpr95-metrics_diff.fpr95
metrics_diff["ash_diff_auroc"] = metrics_ash.auroc-metrics_diff.auroc
metrics_diff["ash_diff_id_acc"] = metrics_ash.id_acc-metrics_diff.id_acc
metrics_diff["react_diff_fpr"] = metrics_ash.fpr95-metrics_diff.fpr95
metrics_diff["react_diff_auroc"] = metrics_ash.auroc-metrics_diff.auroc
metrics_diff["react_diff_id_acc"] = metrics_ash.fpr95-metrics_diff.fpr95

In [47]:
metrics_diff

,index,method,dataset,fpr95,auroc,id_acc,ash_diff_fpr,ash_diff_auroc,ash_diff_id_acc,react_diff_fpr,react_diff_auroc,react_diff_id_acc
0,0,msp,UCF,40.593,88.000,86.773,0.912,-1.568,-0.57,0.912,-1.568,0.912
1,1,msp,HAC,28.620,91.568,86.773,0.114,-1.240,-0.57,0.114,-1.240,0.114
2,2,msp,EPIC,13.455,96.422,86.773,3.535,-2.105,-0.57,3.535,-2.105,3.535
3,9,ebo,UCF,37.058,89.712,86.773,1.711,-0.160,-0.57,1.711,-0.160,1.711
4,10,ebo,HAC,23.033,94.447,86.773,0.456,0.035,-0.57,0.456,0.035,0.456
5,11,ebo,EPIC,7.184,97.598,86.773,-0.228,0.653,-0.57,-0.228,0.653,-0.228
6,18,maxlogit,UCF,37.058,89.729,86.773,1.711,-0.231,-0.57,1.711,-0.231,1.711
7,19,maxlogit,HAC,23.147,94.250,86.773,0.456,0.098,-0.57,0.456,0.098,0.456
8,20,maxlogit,EPIC,7.070,97.726,86.773,0.228,0.374,-0.57,0.228,0.374,0.228
9,27,Mahalanobis,UCF,27.708,91.211,86.773,20.639,-10.357,-0.57,20.639,-10.357,20.639
10,28,Mahalanobis,HAC,7.754,98.218,86.773,23.033,-6.998,-0.57,23.033,-6.998,23.033
11,29,Mahalanobis,EPIC,12.429,96.100,86.773,27.708,-12.632,-0.57,27.708,-12.632,27.708
12,42,gen,UCF,37.400,91.235,86.773,1.369,-1.683,-0.57,1.369,-1.683,1.369
13,43,gen,HAC,24.287,94.326,86.773,-0.798,0.156,-0.57,-0.798,0.156,-0.798
14,44,gen,EPIC,5.131,99.024,86.773,1.825,-0.773,-0.57,1.825,-0.773,1.825
15,51,knn,UCF,33.181,91.948,86.773,4.219,-1.773,-0.57,4.219,-1.773,4.219
16,52,knn,HAC,13.569,97.248,86.773,12.315,-3.171,-0.57,12.315,-3.171,12.315
17,53,knn,EPIC,5.587,98.990,86.773,0.912,-0.512,-0.57,0.912,-0.512,0.912
18,60,vim,UCF,26.910,92.274,86.773,10.946,-3.175,-0.57,10.946,-3.175,10.946
19,61,vim,HAC,6.385,98.563,86.773,15.964,-4.367,-0.57,15.964,-4.367,15.964
20,62,vim,EPIC,5.587,98.062,86.773,7.412,-0.876,-0.57,7.412,-0.876,7.412