Est-ce qu'il y a une corrélation entre la variation du MSP quand on introduit React dans la modalité et le poids donné par le classifieur à cette modalité.

In [2]:
import pandas as pd
import numpy as np
import os

Charger les MSP (fichiers *conf*) avec react pour chaque moda, et sans react, et comparer

# Far OOD

In [3]:
#Poids far ood: [-1.6564, -1.9537, -2.4476, -2.4168]
poids_far_ood = ["poids_far_ood", -1.9537, -2.4476, -2.4168, 0]

In [4]:
root_dir = "/data/maouche/MultiOOD/HMDB-rgb-flow/saved_files/"
ood_datasets = ['UCF', 'EPIC', 'HAC']
modalities = ['video', 'flow']

In [5]:
template_id_sans_react =  "id_HMDB_conf_baseline_best_val.npy"
template_id_react_tout = "id_HMDB_conf_baseline_best_react_val.npy"
template_id_par_modalite = "id_HMDB_conf_baseline_best_react_{}_val.npy"

# Sans react
conf_sans_react = np.load(root_dir+template_id_sans_react)
conf_sans_react = conf_sans_react.reshape(conf_sans_react.shape[0], 1)

# # React sur tout
conf_react_tout = np.load(root_dir+template_id_react_tout)
conf_react_tout = conf_react_tout.reshape(conf_react_tout.shape[0], 1)


# React par modalité
conf_une_modalite = []
for modality in modalities:
    x = np.load(root_dir+template_id_par_modalite.format(modality))
    x = x.reshape(x.shape[0], 1)
    conf_une_modalite.append(x)
conf_une_modalite = np.hstack(conf_une_modalite)

In [6]:
diff_react_video = np.mean(conf_sans_react - conf_une_modalite[0])
diff_react_flow = np.mean(conf_sans_react - conf_une_modalite[1])

diff_react_video_inv = np.mean(conf_react_tout - conf_une_modalite[0])
diff_react_flow_inv = np.mean(conf_react_tout - conf_une_modalite[1])

diff_react_tout = np.mean(conf_sans_react - conf_react_tout)

diffs_far_ood_id = ["far_ood_id", diff_react_tout, diff_react_video, diff_react_flow, 0]

In [7]:
print("Changement MSP avec react video : ", -np.round(diff_react_video,4))
print("Changement MSP avec react flow : ", -np.round(diff_react_flow,4))
print("Changement MSP avec react video p.r react tout : ", -np.round(diff_react_video_inv,4))
print("Changement MSP avec react flow p.r à react tout : ", -np.round(diff_react_flow_inv,4))
print("Changement MSP avec react tout : ", -np.round(diff_react_tout,4))

Changement MSP avec react video :  0.0527
Changement MSP avec react flow :  0.0522
Changement MSP avec react video p.r react tout :  0.0616
Changement MSP avec react flow p.r à react tout :  0.0611
Changement MSP avec react tout :  -0.0089

Données OOD

In [8]:
template_sans_react =  "id_HMDB_ood_{}_conf_baseline_best_eval.npy"
template_react_tout = "id_HMDB_ood_{}_conf_baseline_best_react_eval.npy"
template_par_modalite = "id_HMDB_ood_{}_conf_baseline_best_react_{}_eval.npy"

# Sans react
conf_sans_react = []
for dataset in ood_datasets:
    x = np.load(root_dir+template_sans_react.format(dataset))
    x = x.reshape(x.shape[0], 1)
    conf_sans_react.append(x)
conf_sans_react = np.vstack(conf_sans_react) #(N,1), avec N = 9603, toutes les vidéos des 3 datasets (selon les filtrages far ood)

# React sur tout 
conf_react_tout = []
for dataset in ood_datasets:
    x = np.load(root_dir+template_react_tout.format(dataset))
    x = x.reshape(x.shape[0], 1)
    conf_react_tout.append(x)
conf_react_tout = np.vstack(conf_react_tout) #(N,1)

# React par modalité
conf_par_modalite = []
for modality in modalities:
    conf_une_modalite = []
    for dataset in ood_datasets:
        x = np.load(root_dir+template_par_modalite.format(dataset, modality))
        x = x.reshape(x.shape[0], 1)
        conf_une_modalite.append(x)
    conf_une_modalite = np.vstack(conf_une_modalite)
    conf_par_modalite.append(conf_une_modalite)

conf_par_modalite = np.reshape(conf_par_modalite, (-1, len(modalities)))  #(N,2)

In [9]:
diff_react_video = np.mean(conf_sans_react - conf_une_modalite[0])
diff_react_flow = np.mean(conf_sans_react - conf_une_modalite[1])

diff_react_video_inv = np.mean(conf_react_tout - conf_une_modalite[0])
diff_react_flow_inv = np.mean(conf_react_tout - conf_une_modalite[1])

diff_react_tout = np.mean(conf_sans_react - conf_react_tout)

diffs_far_ood_ood = ["far_ood_ood", diff_react_tout, diff_react_video, diff_react_flow, 0]

In [10]:
print("Changement MSP avec react video : ", -np.round(diff_react_video,4))
print("Changement MSP avec react flow : ", -np.round(diff_react_flow,4))
print("Changement MSP avec react video p.r react tout : ", -np.round(diff_react_video_inv,4))
print("Changement MSP avec react flow p.r à react tout : ", -np.round(diff_react_flow_inv,4))
print("Changement MSP avec react tout : ", -np.round(diff_react_tout,4))

Changement MSP avec react video :  -0.1621
Changement MSP avec react flow :  0.0472
Changement MSP avec react video p.r react tout :  -0.1275
Changement MSP avec react flow p.r à react tout :  0.0818
Changement MSP avec react tout :  -0.0346

# Near OOD VFA

In [11]:
# Poids: [-0.3192, -0.0850, -0.2925, -0.6136, -0.7615]
poids_near_ood = ["poids_near_ood", -0.0850, -0.2925, -0.6136, -0.7615]

In [12]:
root_dir = "/data/maouche/MultiOOD/EPIC-rgb-flow/saved_files/"
modalities = ['video', 'flow', "audio"]

In [13]:
template_sans_react =  "id_EPIC_near_ood_conf_vfa_baseline_best_test.npy"
template_react_tout = "id_EPIC_near_ood_conf_vfa_baseline_best_react_test.npy"
template_par_modalite = "id_EPIC_near_ood_conf_vfa_baseline_best_react_{}_test.npy"

# Sans react
conf_sans_react = np.load(root_dir+template_sans_react)
conf_sans_react = conf_sans_react.reshape(conf_sans_react.shape[0], 1)

# React sur tout
conf_react_tout = np.load(root_dir+template_react_tout)
conf_react_tout = conf_react_tout.reshape(conf_react_tout.shape[0], 1)


# React par modalité
conf_une_modalite = []
for modality in modalities:
    x = np.load(root_dir+template_par_modalite.format(modality))
    x = x.reshape(x.shape[0], 1)
    conf_une_modalite.append(x)
conf_une_modalite = np.hstack(conf_une_modalite)

#dataset_id = np.hstack([conf_sans_react, conf_react_tout, conf_une_modalite]) #(N,5)

In [14]:
diff_react_video = np.mean(conf_sans_react - conf_une_modalite[0])
diff_react_flow = np.mean(conf_sans_react - conf_une_modalite[1])
diff_react_audio = np.mean(conf_sans_react - conf_une_modalite[2])

diff_react_video_inv = np.mean(conf_react_tout - conf_une_modalite[0])
diff_react_flow_inv = np.mean(conf_react_tout - conf_une_modalite[1])
diff_react_audio_inv = np.mean(conf_react_tout - conf_une_modalite[2])

diff_react_tout = np.mean(conf_sans_react - conf_react_tout)

diffs_near_ood_vfa_id = ["near_ood_vfa_id", diff_react_tout, diff_react_video, diff_react_flow, diff_react_audio]

In [15]:
print("Changement MSP avec react video : ", -np.round(diff_react_video,4))
print("Changement MSP avec react flow : ", -np.round(diff_react_flow,4))
print("Changement MSP avec react audio : ", -np.round(diff_react_audio,4))
print("Changement MSP avec react video p.r react tout : ", -np.round(diff_react_video_inv,4))
print("Changement MSP avec react flow p.r à react tout : ", -np.round(diff_react_flow_inv,4))
print("Changement MSP avec react audio p.r à react tout : ", -np.round(diff_react_audio_inv,4))
print("Changement MSP avec react tout : ", -np.round(diff_react_tout,4))

Changement MSP avec react video :  0.0815
Changement MSP avec react flow :  0.1039
Changement MSP avec react audio :  0.1159
Changement MSP avec react video p.r react tout :  0.1061
Changement MSP avec react flow p.r à react tout :  0.1284
Changement MSP avec react audio p.r à react tout :  0.1405
Changement MSP avec react tout :  -0.0246

Données OOD

In [16]:
template_sans_react =  "id_EPIC_near_ood_conf_vfa_baseline_best_eval.npy"
template_react_tout = "id_EPIC_near_ood_conf_vfa_baseline_best_react_eval.npy"
template_par_modalite = "id_EPIC_near_ood_conf_vfa_baseline_best_react_{}_eval.npy"

# Sans react
conf_sans_react = np.load(root_dir+template_sans_react)
conf_sans_react = conf_sans_react.reshape(conf_sans_react.shape[0], 1)

# React sur tout
conf_react_tout = np.load(root_dir+template_react_tout)
conf_react_tout = conf_react_tout.reshape(conf_react_tout.shape[0], 1)


# React par modalité
conf_une_modalite = []
for modality in modalities:
    x = np.load(root_dir+template_par_modalite.format(modality))
    x = x.reshape(x.shape[0], 1)
    conf_une_modalite.append(x)
conf_une_modalite = np.hstack(conf_une_modalite)


dataset_ood = np.hstack([conf_sans_react, conf_react_tout, conf_une_modalite]) #(N,5)

In [17]:
diff_react_video = np.mean(conf_sans_react - conf_une_modalite[0])
diff_react_flow = np.mean(conf_sans_react - conf_une_modalite[1])
diff_react_audio = np.mean(conf_sans_react - conf_une_modalite[2])

diff_react_video_inv = np.mean(conf_react_tout - conf_une_modalite[0])
diff_react_flow_inv = np.mean(conf_react_tout - conf_une_modalite[1])
diff_react_audio_inv = np.mean(conf_react_tout - conf_une_modalite[2])

diff_react_tout = np.mean(conf_sans_react - conf_react_tout)

diffs_near_ood_vfa_ood = ["near_ood_vfa_ood", diff_react_tout, diff_react_video, diff_react_flow, diff_react_audio]

In [18]:
print("Changement MSP avec react video : ", -np.round(diff_react_video,4))
print("Changement MSP avec react flow : ", -np.round(diff_react_flow,4))
print("Changement MSP avec react audio : ", -np.round(diff_react_audio,4))
print("Changement MSP avec react video p.r react tout : ", -np.round(diff_react_video_inv,4))
print("Changement MSP avec react flow p.r à react tout : ", -np.round(diff_react_flow_inv,4))
print("Changement MSP avec react audio p.r à react tout : ", -np.round(diff_react_audio_inv,4))
print("Changement MSP avec react tout : ", -np.round(diff_react_tout,4))

Changement MSP avec react video :  -0.2827
Changement MSP avec react flow :  -0.1414
Changement MSP avec react audio :  -0.1082
Changement MSP avec react video p.r react tout :  -0.2693
Changement MSP avec react flow p.r à react tout :  -0.1281
Changement MSP avec react audio p.r à react tout :  -0.0949
Changement MSP avec react tout :  -0.0134

In [19]:
df = pd.DataFrame([poids_far_ood, diffs_far_ood_id, diffs_far_ood_ood, poids_near_ood, diffs_near_ood_vfa_id, diffs_near_ood_vfa_ood], columns = ["config", 'tout', 'video', 'flow', 'audio'])
df

             config      tout     video      flow     audio
0     poids_far_ood -1.953700 -2.447600 -2.416800  0.000000
1        far_ood_id  0.008893 -0.052706 -0.052168  0.000000
2       far_ood_ood  0.034578  0.162056 -0.047192  0.000000
3    poids_near_ood -0.085000 -0.292500 -0.613600 -0.761500
4   near_ood_vfa_id  0.024589 -0.081540 -0.103855 -0.115929
5  near_ood_vfa_ood  0.013353  0.282672  0.141440  0.108242

In [ ]:
#df.to_csv("correlations_comparaison.csv", index=False)
df = pd.read_csv("correlations_comparaison.csv")

# Coefficients de corrélation

In [48]:
df_far = df.iloc[:3].drop("audio", axis=1)
poids = df_far[df_far.config=="poids_far_ood"].drop("config", axis=1).iloc[0].values
delta_id = df_far[df_far.config=="far_ood_id"].drop("config", axis=1).iloc[0].values
delta_ood = df_far[df_far.config=="far_ood_ood"].drop("config", axis=1).iloc[0].values
correlation_far_id = np.corrcoef(poids, delta_id)[0,1]
correlation_far_ood = np.corrcoef(poids, delta_ood)[0,1]
print(f"{correlation_far_id=}, {correlation_far_ood=}")

correlation_far_id=0.9988438013417865, correlation_far_ood=-0.18015313933099317

In [49]:
df_near = df.iloc[3:]
poids = df_near[df_near.config=="poids_near_ood"].drop("config", axis=1).iloc[0].values
delta_id = df_near[df_near.config=="near_ood_vfa_id"].drop("config", axis=1).iloc[0].values
delta_ood = df_near[df_near.config=="near_ood_vfa_ood"].drop("config", axis=1).iloc[0].values
correlation_near_id = np.corrcoef(poids, delta_id)[0,1]
correlation_near_ood = np.corrcoef(poids, delta_ood)[0,1]
print(f"{correlation_near_id=}, {correlation_near_ood=}")

correlation_near_id=0.891622284374432, correlation_near_ood=-0.1358900589564517

# Ash

In [3]:
root_dir = "/data/maouche/MultiOOD/HMDB-rgb-flow/saved_files/"
ood_datasets = ["EPIC"]
modalities = ['video', 'flow', 'audio']

In [4]:
poids_far_ood = ["poids_far_ood", -8.2436,  4.2558, -5.5319, -1.8816] #, -1.9537, -2.4476, -2.4168, 0]
poids_near_ood = ["poids_near_ood", -1.0723,  0.0707, -1.0293, -1.6733, -0.5044]#, -1.9537, -2.4476, -2.4168, 0]

Far

ID

In [5]:
template_id_sans_ash =  "id_HMDB_conf_baseline_best_val.npy"
template_id_ash_tout = "id_HMDB_conf_baseline_best_ash_val.npy"
template_id_par_modalite = "id_HMDB_conf_baseline_best_ash_{}_val.npy"

# Sans ash
conf_sans_ash = np.load(root_dir+template_id_sans_ash)
conf_sans_ash = conf_sans_ash.reshape(conf_sans_ash.shape[0], 1)

# # React sur tout
conf_ash_tout = np.load(root_dir+template_id_ash_tout)
conf_ash_tout = conf_ash_tout.reshape(conf_ash_tout.shape[0], 1)


# React par modalité
conf_une_modalite = []
for modality in modalities:
    x = np.load(root_dir+template_id_par_modalite.format(modality))
    x = x.reshape(x.shape[0], 1)
    conf_une_modalite.append(x)
conf_une_modalite = np.hstack(conf_une_modalite)

FileNotFoundError: [Errno 2] No such file or directory: '/data/maouche/MultiOOD/HMDB-rgb-flow/saved_files/id_HMDB_conf_baseline_best_ash_audio_val.npy'

In [ ]:
diff_ash_video = np.mean(conf_sans_ash - conf_une_modalite[0])
diff_ash_flow = np.mean(conf_sans_ash - conf_une_modalite[1])

diff_ash_video_inv = np.mean(conf_ash_tout - conf_une_modalite[0])
diff_ash_flow_inv = np.mean(conf_ash_tout - conf_une_modalite[1])

diff_ash_tout = np.mean(conf_sans_ash - conf_ash_tout)

diffs_far_ood_id = ["far_ood_id", diff_ash_tout, diff_ash_video, diff_ash_flow, 0]

Données OOD

In [ ]:
template_sans_ash =  "id_HMDB_ood_{}_conf_baseline_best_eval.npy"
template_ash_tout = "id_HMDB_ood_{}_conf_baseline_best_ash_eval.npy"
template_par_modalite = "id_HMDB_ood_{}_conf_baseline_best_ash_{}_eval.npy"

# Sans ash
conf_sans_ash = []
for dataset in ood_datasets:
    x = np.load(root_dir + template_sans_ash.format(dataset))
    x = x.reshape(x.shape[0], 1)
    conf_sans_ash.append(x)
conf_sans_ash = np.vstack(conf_sans_ash)  # (N,1), avec N = 9603, toutes les vidéos des 3 datasets (selon les filtrages far ood)

# Ash sur tout 
conf_ash_tout = []
for dataset in ood_datasets:
    x = np.load(root_dir + template_ash_tout.format(dataset))
    x = x.reshape(x.shape[0], 1)
    conf_ash_tout.append(x)
conf_ash_tout = np.vstack(conf_ash_tout)  # (N,1)

# Ash par modalité
conf_par_modalite = []
for modality in modalities:
    conf_une_modalite = []
    for dataset in ood_datasets:
        x = np.load(root_dir + template_par_modalite.format(dataset, modality))
        x = x.reshape(x.shape[0], 1)
        conf_une_modalite.append(x)
    conf_une_modalite = np.vstack(conf_une_modalite)
    conf_par_modalite.append(conf_une_modalite)

conf_par_modalite = np.reshape(conf_par_modalite, (-1, len(modalities)))  # (N,2)

In [ ]:
diff_ash_video = np.mean(conf_sans_ash - conf_une_modalite[0])
diff_ash_flow = np.mean(conf_sans_ash - conf_une_modalite[1])

diff_ash_video_inv = np.mean(conf_ash_tout - conf_une_modalite[0])
diff_ash_flow_inv = np.mean(conf_ash_tout - conf_une_modalite[1])

diff_ash_tout = np.mean(conf_sans_ash - conf_ash_tout)

diffs_far_ood_ood = ["far_ood_ood", diff_ash_tout, diff_ash_video, diff_ash_flow, 0]

Near

In [ ]:
template_sans_ash =  "id_EPIC_near_ood_conf_vfa_baseline_best_test.npy"
template_ash_tout = "id_EPIC_near_ood_conf_vfa_baseline_best_ash_test.npy"
template_par_modalite = "id_EPIC_near_ood_conf_vfa_baseline_best_ash_{}_test.npy"

# Sans ash
conf_sans_ash = np.load(root_dir + template_sans_ash)
conf_sans_ash = conf_sans_ash.reshape(conf_sans_ash.shape[0], 1)

# Ash sur tout
conf_ash_tout = np.load(root_dir + template_ash_tout)
conf_ash_tout = conf_ash_tout.reshape(conf_ash_tout.shape[0], 1)

# Ash par modalité
conf_une_modalite = []
for modality in modalities:
    x = np.load(root_dir + template_par_modalite.format(modality))
    x = x.reshape(x.shape[0], 1)
    conf_une_modalite.append(x)
conf_une_modalite = np.hstack(conf_une_modalite)

# dataset_id = np.hstack([conf_sans_ash, conf_ash_tout, conf_une_modalite])  # (N,5)

In [ ]:
diff_ash_video = np.mean(conf_sans_ash - conf_une_modalite[0])
diff_ash_flow = np.mean(conf_sans_ash - conf_une_modalite[1])
diff_ash_audio = np.mean(conf_sans_ash - conf_une_modalite[2])

diff_ash_video_inv = np.mean(conf_ash_tout - conf_une_modalite[0])
diff_ash_flow_inv = np.mean(conf_ash_tout - conf_une_modalite[1])
diff_ash_audio_inv = np.mean(conf_ash_tout - conf_une_modalite[2])

diff_ash_tout = np.mean(conf_sans_ash - conf_ash_tout)

diffs_near_ood_vfa_id = ["near_ood_vfa_id", diff_ash_tout, diff_ash_video, diff_ash_flow, diff_ash_audio]

ood

In [ ]:
template_sans_ash =  "id_EPIC_near_ood_conf_vfa_baseline_best_eval.npy"
template_ash_tout = "id_EPIC_near_ood_conf_vfa_baseline_best_ash_eval.npy"
template_par_modalite = "id_EPIC_near_ood_conf_vfa_baseline_best_ash_{}_eval.npy"

# Sans ash
conf_sans_ash = np.load(root_dir + template_sans_ash)
conf_sans_ash = conf_sans_ash.reshape(conf_sans_ash.shape[0], 1)

# Ash sur tout
conf_ash_tout = np.load(root_dir + template_ash_tout)
conf_ash_tout = conf_ash_tout.reshape(conf_ash_tout.shape[0], 1)

# Ash par modalité
conf_une_modalite = []
for modality in modalities:
    x = np.load(root_dir + template_par_modalite.format(modality))
    x = x.reshape(x.shape[0], 1)
    conf_une_modalite.append(x)
conf_une_modalite = np.hstack(conf_une_modalite)

dataset_ood = np.hstack([conf_sans_ash, conf_ash_tout, conf_une_modalite])  # (N,5)

In [ ]:
diff_ash_video = np.mean(conf_sans_ash - conf_une_modalite[0])
diff_ash_flow = np.mean(conf_sans_ash - conf_une_modalite[1])
diff_ash_audio = np.mean(conf_sans_ash - conf_une_modalite[2])

diff_ash_video_inv = np.mean(conf_ash_tout - conf_une_modalite[0])
diff_ash_flow_inv = np.mean(conf_ash_tout - conf_une_modalite[1])
diff_ash_audio_inv = np.mean(conf_ash_tout - conf_une_modalite[2])

diff_ash_tout = np.mean(conf_sans_ash - conf_ash_tout)

diffs_near_ood_vfa_ood = ["near_ood_vfa_ood", diff_ash_tout, diff_ash_video, diff_ash_flow, diff_ash_audio]

In [ ]:
df = pd.DataFrame([poids_far_ood, diffs_far_ood_id, diffs_far_ood_ood, poids_near_ood, diffs_near_ood_vfa_id, diffs_near_ood_vfa_ood], columns = ["config", 'tout', 'video', 'flow', 'audio'])
df

             config      tout     video      flow     audio
0     poids_far_ood -1.953700 -2.447600 -2.416800  0.000000
1        far_ood_id  0.008893 -0.052706 -0.052168  0.000000
2       far_ood_ood  0.034578  0.162056 -0.047192  0.000000
3    poids_near_ood -0.085000 -0.292500 -0.613600 -0.761500
4   near_ood_vfa_id  0.024589 -0.081540 -0.103855 -0.115929
5  near_ood_vfa_ood  0.013353  0.282672  0.141440  0.108242

In [ ]:
#df.to_csv("correlations_comparaison_ash.csv", index=False)
df = pd.read_csv("correlations_comparaison_ash.csv")

Correlation

In [ ]:
df_far = df.iloc[:3].drop("audio", axis=1)
poids = df_far[df_far.config=="poids_far_ood"].drop("config", axis=1).iloc[0].values
delta_id = df_far[df_far.config=="far_ood_id"].drop("config", axis=1).iloc[0].values
delta_ood = df_far[df_far.config=="far_ood_ood"].drop("config", axis=1).iloc[0].values
correlation_far_id = np.corrcoef(poids, delta_id)[0,1]
correlation_far_ood = np.corrcoef(poids, delta_ood)[0,1]
print(f"{correlation_far_id=}, {correlation_far_ood=}")

correlation_far_id=0.9988438013417865, correlation_far_ood=-0.18015313933099317

In [ ]:
df_near = df.iloc[3:]
poids = df_near[df_near.config=="poids_near_ood"].drop("config", axis=1).iloc[0].values
delta_id = df_near[df_near.config=="near_ood_vfa_id"].drop("config", axis=1).iloc[0].values
delta_ood = df_near[df_near.config=="near_ood_vfa_ood"].drop("config", axis=1).iloc[0].values
correlation_near_id = np.corrcoef(poids, delta_id)[0,1]
correlation_near_ood = np.corrcoef(poids, delta_ood)[0,1]
print(f"{correlation_near_id=}, {correlation_near_ood=}")

correlation_near_id=0.891622284374432, correlation_near_ood=-0.1358900589564517